name: Ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:  
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.3.1  
      
    - name: Build the Solution
      run: msbuild WpfTest.sln /p:Configuration=Release
      
    - name: Create Release
  # You may pin to the exact commit or the version.
  # uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e
      uses: ncipollo/release-action@v1.12.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: false
            prerelease: false
